package com.planilla.empleado.configuration;

import java.util.Arrays;
import java.util.List;

public class ENVIROMENT {
    public static List<String> getCargos(){
        return Arrays.asList(
                "Air Loader  Ass",
                "Air Loader Op",
                "Alimak  Mech",
                "LH Ass",
                "Locomotora Ass",
                "Trituradora Ass",
                "Bandero ",
                "Bolter Ass",
                "Bolter Op",
                "Camion Op",
                "Capitan",
                "Cargador ",
                "CONT.VOLADURA",
                "ENCARGADO",
                "Jackleg Op  ",
                "Jackleg Ass",
                "Jackleg Ayud Rehabilitacion",
                "Jackleg Op  Rehabilitacion",
                "Jumbo Ass",
                "Jumbo Op",
                "Limpiador chutes",
                "Martillo",
                "Motonivelador Op",
                "OP D5 ",
                "Op DL311",
                "Op LH Drill",
                "Op Locomotora",
                "OP PLANTA",
                "Op Scoop",
                "Op Trituradora",
                "OPERARIO",
                "Scissor Ass",
                "Scissor Op",
                "Supervisor",
                "Winch Op",
                "AGUATEROS",
                "ALBAÑIL",
                "Aseo Casa de Cambio",
                "Asistente General",
                "Operario",
                "Aux. y Jefe  Admis.",
                "Servicios Auxiliares",
                "BOMBERO",
                "Capacitador",
                "Chequeo Mov.E",
                "JEFE ",
                "LIMPIEZA 1975",
                "Op Ceconin",
                "Encargado",
                "Op Locomotora",
                "Paramedico Mina",
                "Polvorin Mina",
                "Sanitarios",
                "SERVICIOS TUBERIAS",
                "SOLDADOR",
                "Superintendente",
                "Supervisor",
                "Time Kepper");
    }
}
